version: 2.1 
jobs:
  compile-job:
    docker:
      - image: quay.io/uuss/us8base
    resource_class: medium
    #resource_class: small
    steps:
      - checkout
      - run:
          name: "Configure code"
          command: |
            cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_FOR_DEBIAN=ON
      - run:
          name: "Build the code"
          command: |
            cmake --build build
      - run:
           name: "Test the code"
           command: |
            cd build
            ctest --verbose
      - run:
           name: "Package code"
           command: |
             cd build
             mkdir -p /tmp/artifacts
             mkdir -p /tmp/workspace
             cpack -B /tmp/artifacts TGZ
             rm -rf /tmp/artifacts/_CPack_Packages
             cp /tmp/artifacts/*-Linux.tar.gz /tmp/workspace/
             cp Dockerfile.deb /tmp/workspace/
             ls /tmp/workspace/
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - Dockerfile.deb
            - uSEEDLinkToDataPacketImportProxy-*
  # End compile job
  deploy-job:
    docker:
      - image: cimg/base:2022.09
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Create docker image"
          command: |
            ls /tmp/workspace/
            cd /tmp/workspace
            ls
            # Figure out version from app-name-MAJOR.MINOR.PATCH-Linux.tar.gz
            tarFile=$(ls *Linux.tar.gz)
            version=$(echo ${tarFile} | sed 's/uSEEDLinkToDataPacketImportProxy-//g' | sed 's/-Linux.tar.gz//g')
            echo ${version}
            docker build -t useedlinktodatapacketimportproxy:${version} -t useedlinktodatapacketimportproxy:latest -f ./Dockerfile.deb .
      - run:
          name: "Quay login"
          command: |
            docker login -u="${QUAY_ROBOT_USER}" -p="${QUAY_ROBOT_PASSWORD}" quay.io
      - run:
          name: "Upload docker image to quay"
          command: |
            docker tag useedlinktodatapacketimportproxy quay.io/uuss/useedlinktodatapacketimportproxy
            docker push quay.io/uuss/useedlinktodatapacketimportproxy

    # End steps
  # End deploy job

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  compile-workflow:
    jobs:
      - compile-job
      - deploy-job:
          requires:
            - compile-job




