version: 2.1 
jobs:
  compile-job:
    docker:
      - image: quay.io/uuss/us8base
    resource_class: medium
    #resource_class: small
    steps:
      - checkout
      - run:
          name: "Configure code"
          command: |
            cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_FOR_DEBIAN=ON
      - run:
          name: "Build the code"
          command: |
            cmake --build build
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - Dockerfile.deb
            - uSEEDLinkToDataPacketImportProxy-*
  # End compile job
  deploy-job:
    docker:
      - image: cimg/base:2022.09
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
    # End steps
  # End deploy job

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  compile-workflow:
    jobs:
      - compile-job
      - deploy-job:
          requires:
            - compile-job




